name = "backend"
compatibility_date = "2024-08-06"

[vars]
DATABASE_URL="	prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOGQyODc1ODEtZDJhNS00NDE3LTg5ODQtZGNmZDlmM2VkMGUyIiwidGVuYW50X2lkIjoiNjZlMGJkMjVkZTI0MzRmMjY4MWQ0YzI4MjE2ZjliYTBkZTVkMTQwN2FlODU2ZDU5ZTczNDEzY2YwZmIyZDhmYiIsImludGVybmFsX3NlY3JldCI6IjM3NTA1ZWQyLTNkNTUtNGM5Ni1hOWIzLThmY2UxNTVjNTJkMiJ9.hKP9HPFGEQYgpfyNex2uhjSU2mBpC8zkaYKGadV4EBU"
JWT_SECRET = "shiva@1234"
